version: '3.8'

services:
  db:
    image: postgres:16
    container_name: slash_db
    environment:
      POSTGRES_DB: slash
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
